scripts/gradle/01-validate-incremental-building.sh
scripts/gradle/02-validate-local-build-caching-same-location.sh
scripts/gradle/03-validate-local-build-caching-different-locations.sh
scripts/gradle/04-validate-remote-build-caching-ci-ci.sh
scripts/gradle/05-validate-remote-build-caching-ci-local.sh
scripts/lib/config.sh
scripts/lib/info.sh
scripts/lib/wizard.sh
scripts/maven/01-validate-local-build-caching-same-location.sh
scripts/maven/02-validate-local-build-caching-different-locations.sh
scripts/maven/03-validate-remote-build-caching-ci-ci.sh
scripts/maven/04-validate-remote-build-caching-ci-local.sh

- Remove blank line printed at the end of interactive mode
- Deduplicate text in the explain_and_print_summary functions across the scripts
- Deduplicate CCUD Plugin preparation step explaination
- Deduplicate other gradle exp prerequisite explainatory text
- Deduplicate preparation explainatory text for Maven experiments
- Fix collecting the root dir for Maven experiments
- Fix indentation when build fails or when fetching a build scan fails

Various build validation script tweaks

---

build.gradle.kts

- Clarify the input declarations to the Shellcheck task
- Move assemble tasks to the build group

Small tweaks to the build script

---

components/scripts/lib/gradle.sh
release/changes.md

When using `project-dir` parameter, build fails as relative path to `init-scripts` is incorrect.
This is happening because we `pushd` twice to the `project-dir` folder
https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/bd457beeba9c57d8e8e2afcf396693e2f3be104d/components/scripts/lib/gradle.sh#L13
and then
https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/bd457beeba9c57d8e8e2afcf396693e2f3be104d/components/scripts/lib/paths.sh#L51
Signed-off-by: Jerome Prinet <jprinet@gradle.com>

Remove unnecessary pushd/popd

---

.github/workflows/build-verification.yml
.github/workflows/development-release.yml
.github/workflows/production-release.yml
settings.gradle.kts

This change enables the remote build cache for all builds. Anonymous
users have read-only build cache access, while CI has read-write.
This change also configures GitHub actions to authenticate with the
build cache.

Enable remote build caching

---

build.gradle.kts
gradle.properties

This change requires removing 2 invocations of `Task.project` at
execution time used to access the project version for the
`copyGradleScripts` and `copyMavenScripts` tasks

Enable configuration caching

---

.github/workflows/build-verification.yml
.github/workflows/development-release.yml
.github/workflows/production-release.yml
.github/workflows/wrapper-upgrade-execution.yml
buildSrc/build.gradle.kts

- Adding toolchain to buildSrc
- Changing existing jdk toolchain version from 8 to 11, to match Github action's provisionned version

Add java toolchain support to buildSrc

---

build.gradle.kts

This change fixes a cache miss that appears when the project is run from
two distinct absolute paths.

Set relative path sensitivity for scripts in `lib`

---

.github/workflows/build-verification.yml
.github/workflows/development-release.yml
.github/workflows/production-release.yml
.github/workflows/wrapper-upgrade-execution.yml

Separating the setup of the Gradle build tool from actual build invocation
is more idiomatic to GH Actions in general, and provides a clearer separation
of responsibilities.

Add "Set up Gradle" step to GHActions workflows

---

components/scripts/gradle/01-validate-incremental-building.sh
components/scripts/gradle/02-validate-local-build-caching-same-location.sh
components/scripts/gradle/03-validate-local-build-caching-different-locations.sh
components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh
components/scripts/lib/gradle.sh
components/scripts/lib/maven.sh
components/scripts/maven/01-validate-local-build-caching-same-location.sh
components/scripts/maven/02-validate-local-build-caching-different-locations.sh
components/scripts/maven/04-validate-remote-build-caching-ci-local.sh

This is helpful for projects which have configured build scan publishing to be done on-demand.

Explicitly enable build scan publishing

---

build.gradle.kts

Bumping com.github.breadmoirai.github-release from 2.3.7 to 2.4.1 causes Github release notes to be auto-generated. This PR desactivates this to keep the previous behavior of specifying the release notes manually.

Do not generate release notes

---

components/scripts/lib/build_scan.sh
release/changes.md

Previously, the arrays containing the build scan data were built using append operations. Since Gradle Exp 05 and Maven Exp 04 fetch build scans twice (once to get the build parameters for the 2nd build), this means the data for the first build was appended to the array twice. When it came time to display the statistics, the scripts always show the data at array index 1 (zero-based indexing), so the statistics for the first build would be displayed.
See #148

Fix build caching stats for Gradle exp 05/Maven exp 04

---

components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/cli/Fields.java
components/scripts/gradle/gradle-init-scripts/configure-remote-build-caching.gradle

This change appends a `/` to the remote build cache URL path if one does not exist in the `configure-remote-build-caching` init script.
The remote build cache URL supplied to the build is unchanged from what is returned in the API (note the **_missing_** `/`).
Fixes #155

Append a trailing slash to the build cache URL

---

components/scripts/lib/cli-parsers/common.m4
components/scripts/lib/cli-parsers/gradle/01-cli-parser.m4
components/scripts/lib/cli-parsers/gradle/02-cli-parser.m4
components/scripts/lib/cli-parsers/gradle/03-cli-parser.m4
components/scripts/lib/cli-parsers/gradle/05-cli-parser.m4
components/scripts/lib/cli-parsers/maven/01-cli-parser.m4
components/scripts/lib/cli-parsers/maven/02-cli-parser.m4
components/scripts/lib/cli-parsers/maven/04-cli-parser.m4
components/scripts/lib/config.sh
components/scripts/lib/git.sh
components/scripts/lib/help.sh

This PR adds the ability to supply additional options the `git clone` by use  of the `--git-options` parameter, or `-o` for short.
Example:
```shell
./01-validate-incremental-building.sh  --git-options '--depth=9999' --tasks build -r 'git@github.com:gradle/gradle-enterprise-build-validation-scripts.git'
```
Experiments affected:
- Gradle: 1, 2, 3, & 5
- Maven: 1, 2, & 4
Notes/questions:
- When checking out a specific commit, which occurs when `--git-commit` is used or always in gradle-exp5 and maven-exp4(?), we `fetch` instead of a `clone`. Should we also supply the value of `--git-options` to `fetch`?
- The common case of wanting to perform a full clone is not directly supported by this change. We are already using `--depth=1` when we `clone` with no way to remove it. A workaround for …

Add `-o`/`--git-options`

---

components/scripts/gradle/04-validate-remote-build-caching-ci-ci.sh
components/scripts/maven/03-validate-remote-build-caching-ci-ci.sh

Previously on Maven experiment 3 and Gradle experiment 4 the Git options would be displayed as `<unknown>`. This change sets the Git options to display as `<not available>` in order to be consistent with other options printed in the summary.
```
-1 'https://ge.solutions-team.gradle.com/s/6x7tulbxvdt66' \
-2 'https://ge.solutions-team.gradle.com/s/xm7udfl7jp4hs'
```
```
./03-validate-remote-build-caching-ci-ci.sh \
-1 'https://ge.solutions-team.gradle.com/s/ed6a3h7m3swpa' \
-2 'https://ge.solutions-team.gradle.com/s/eq5u5tbq6xdyo'
```

Print `<not available>` for Git options on exp4-gradle and exp3-maven

---

components/scripts/gradle/03-validate-local-build-caching-different-locations.sh
components/scripts/lib/cli-parsers/gradle/03-cli-parser.m4
components/scripts/lib/config.sh

The `--no` prefix was confusing Argbash, which supports turning boolean flags
off with `--no-` prefixes.  The solution is to define a `build-scan-publishing`
flag instead, but default it to 'on'.

Fix --no-build-scan-publishing

---

components/scripts/gradle/03-validate-local-build-caching-different-locations.sh
components/scripts/lib/gradle.sh
components/scripts/lib/info.sh

Summary when `--no-build-scan-publishing` is passed:
```
Summary
-------
Project:                      java-ordered-properties
Git repo:                     https://github.com/etiennestuder/java-ordered-properties
Git branch:                   ge
Git commit id:                b471d917952df7fcc2fab937d404365c4e3e4b4f
Git options:                  --depth=1
Project dir:                  <root directory>
Gradle tasks:                 assemble
Gradle arguments:             <none>
Experiment:                   03 Validate local build caching - different project locations
Experiment id:                exp3-gradle
Experiment run id:            635c2803
Experiment artifact dir:      .data/03-validate-local-build-caching-different-locations/20221028T150539-635c2803
Build scan first build: …
```

Adjust experiment summary for --no-build-scan-published

---

components/scripts/gradle/03-validate-local-build-caching-different-locations.sh
components/scripts/lib/cli-parsers/gradle/03-cli-parser.m4
components/scripts/lib/config.sh
components/scripts/lib/help.sh
components/scripts/lib/info.sh
components/scripts/lib/wizard.sh

```
./03-validate-local-build-caching-different-locations.sh -r https://github.com/etiennestuder/java-ordered-properties \
-b ge \
-t assemble \
--no-build-scan-publishing \
-- debug
```
```
./03-validate-local-build-caching-different-locations.sh --help
```
```
./03-validate-local-build-caching-different-locations.sh -r https://github.com/etiennestuder/java-ordered-properties \
-b ge \
-t assemble \
--no-build-scan-publishing \
--interactive
```
```
./03-validate-local-build-caching-different-locations.sh -r https://github.com/etiennestuder/java-ordered-properties \
-b ge \
-t assemble \
--no-build-scan-publishing
```
```
./03-validate-local-build-caching-different-locations.sh -r https://github.com/etiennestuder/java-ordered-properties \
-b ge \
-t assemble \
--no-build-scan-publishing …
```

Improve text and guidance when Build Scan publishing is disabled

---

components/scripts/gradle/03-validate-local-build-caching-different-locations.sh
components/scripts/lib/cli-parsers/gradle/03-cli-parser.m4
components/scripts/lib/config.sh
components/scripts/lib/wizard.sh

- Replace --no-build-scan-publishing with --disable-build-scan-publishing
- Eliminate extra blank line in interactive mode when build scan publishing is disabled

Rename --no-build-scan-publishing to --disable-build-scan-publishing

---

components/scripts/lib/config.sh
components/scripts/lib/gradle.sh
components/scripts/lib/maven.sh

If Build Scan publishing is disabled, then the GE server used doesn't matter.
It isn't captured in the Build Scan dumps, and even if it was, it wouldn't
affect the experiment.
As such, if the user provides `--enable-gradle-enterprise` along with
`--disable-build-scan-publishing`, then no longer require the user to also
provide `--gradle-enterprise-server`.
Unfortunately, the Gradle Enterprise plugin and Maven extension still require a
server to run, so we want to set the server to a dummy value, but only if the
user isn't setting `--gradle-enterprise-server` themselves.

Do not require the user to provide a GE server if Build Scan publishing is disabled

---

.github/workflows/build-verification.yml
.github/workflows/development-release.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/production-release.yml
.github/workflows/wrapper-upgrade-execution.yml

Deprecation warnings appear when running actions/checkout@v2, this is fixed when upgrading to actions/checkout@v3

Upgrade Github actions/checkout to v3

---

.github/workflows/cross-platform-testing.yml

Some operating system versions have been deprecated, while others have been added.
Note that we can't test against windows-2022 because WSL v1 is not supported on Windows Server 2022.

Adjust the cross-platform-tests target operating systems 

---

.github/actions/gradle/experiment-1/action.yml
.github/actions/gradle/experiment-2/action.yml
.github/actions/gradle/experiment-3/action.yml
.github/actions/maven/experiment-1/action.yml
.github/actions/maven/experiment-2/action.yml
.github/workflows/build-verification.yml
.github/workflows/cross-platform-testing.yml
.github/workflows/development-release.yml
.github/workflows/production-release.yml
.github/workflows/wrapper-upgrade-execution.yml

Update some Github actions and remove ::set-output to get rid of deprecation warnings
[Some deprecation warnings are left](https://github.com/gradle/gradle-enterprise-build-validation-scripts/actions/runs/3498266802):
- ubuntu-18.04 runner is deprecated 
- macos-10.15 runner is deprecated

Update some Github actions and remove ::set-output

---

components/scripts/gradle/03-validate-local-build-caching-different-locations.sh
components/scripts/lib/gradle.sh

1. Checkout this branch `erichaagdev/parse-scan-dump`
2. Run `./gradlew clean build`
3. `cd build/distributions`
4. `unzip gradle-enterprise-gradle-build-validation-dev.zip`
5. `cd gradle-enterprise-gradle-build-validation`
6. Download a copy of the `build-scan-support-tool.jar` and place it in the current directory. It must be named exactly `build-scan-support-tool.jar`.
7. Run! 
```shell
./03-validate-local-build-caching-different-locations.sh \
--git-repo 'https://github.com/etiennestuder/java-ordered-properties' \
--git-branch ge \
--tasks build \
--disable-build-scan-publishing
```
Here is an example of what it looks like when the `build-scan-support-tool.jar` is not found in the same directory as the validation scripts.
Additionally, the message "Extracting build scan data, done." …

Use Build Scan dumps when publishing is disabled for Gradle experiment 3

---

components/scripts/gradle/03-validate-local-build-caching-different-locations.sh

When both `--build-scan-publishing-disabled` and `--project-dir` are used, the supplied project directory is not currently considered when searching for the Build Scan file. To test these changes, I ran the following command before and after my changes:
```shell
./03-validate-local-build-caching-different-locations.sh \
-r 'git@github.com:erichaagdev/openapi-generator.git' \
-b 'upgrade-gradle-7.5.1' \
-p 'modules/openapi-generator-gradle-plugin' \
-t assemble \
-x -e
```
Closes #217

Append project directory to build directory when running with Build Scan publishing disabled

---

.github/actions/gradle/experiment-1/action.yml
.github/actions/gradle/experiment-2/action.yml
.github/actions/gradle/experiment-3/action.yml
.github/actions/maven/experiment-1/action.yml
.github/actions/maven/experiment-2/action.yml

I changed the processing of `enableGradleEnterprise` flag as well to allow true/false configuration.
Previous behavior was to enable the flag as soon as the value was not empty

Add fail if not fully cacheable flag to GH composite workflows

---

components/scripts/gradle/01-validate-incremental-building.sh
components/scripts/gradle/02-validate-local-build-caching-same-location.sh
components/scripts/gradle/03-validate-local-build-caching-different-locations.sh
components/scripts/gradle/04-validate-remote-build-caching-ci-ci.sh
components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh
components/scripts/lib/config.sh
components/scripts/lib/wizard.sh
components/scripts/maven/01-validate-local-build-caching-same-location.sh
components/scripts/maven/02-validate-local-build-caching-different-locations.sh
components/scripts/maven/03-validate-remote-build-caching-ci-ci.sh
components/scripts/maven/04-validate-remote-build-caching-ci-local.sh

If the experiment needs to be interrupted for some reason, it's rather annoying
to have to re-enter all of the settings when re-running the experiment. We show
the command to repeat the experiment at the end of the summary, but that's only
helpful if the script completes normally.
This commit updates interactive mode to also show the command to repeat the
experiment immediately after all of the configuration options have been
collected, but before executing any of the builds.

Users understand the cmd line arguments as soon as they have provided all information in interactive mode

---

components/scripts/gradle/04-validate-remote-build-caching-ci-ci.sh
components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh
components/scripts/maven/03-validate-remote-build-caching-ci-ci.sh
components/scripts/maven/04-validate-remote-build-caching-ci-local.sh
release/changes.md

```shell
./03-validate-remote-build-caching-ci-ci.sh \
-1 'https://ge.solutions-team.gradle.com/s/ed6a3h7m3swpa' \
-2 'https://ge.solutions-team.gradle.com/s/eq5u5tbq6xdyo' \
--fail-if-not-fully-cacheable \
--interactive
```
```shell
./04-validate-remote-build-caching-ci-local.sh \
-1 'https://ge.solutions-team.gradle.com/s/ed6a3h7m3swpa' \
--args '-DskipTests' \
--remote-build-cache-url 'https://ge.solutions-team.gradle.com/cache' \
--fail-if-not-fully-cacheable \
--interactive
```
```shell
-1 https://ge.solutions-team.gradle.com/s/k2gzrbklej2eq \
-2 https://ge.solutions-team.gradle.com/s/2dn2py4gxhm7y \
--fail-if-not-fully-cacheable \
--interactive
```
```shell
./05-validate-remote-build-caching-ci-local.sh \
-1 …
```

Add missing `-f` on command to repeat experiment for several experiments

---

components/scripts/maven/01-validate-local-build-caching-same-location.sh
components/scripts/maven/02-validate-local-build-caching-different-locations.sh
release/changes.md

I was able to recreate this issue as seen in the following [Build Scan](https://ge.solutions-team.gradle.com/s/nof5ijxxb53ju/performance/build-cache#local-cache-store).
Using the exact same code base, I reran the experiments and saw local cache pushing was enabled as can be seen in the following Build Scans: 
- [exp1-maven](https://ge.solutions-team.gradle.com/s/owhf3ct5garna/performance/build-cache#local-cache-store)
- [exp2-maven](https://ge.solutions-team.gradle.com/s/b3zoslui6sl4y/performance/build-cache#local-cache-store)
You can also see the builds benefited from the local cache as expected.
Closes #227

Ensure correctness of `storeEnabled` for local caching in Maven experiments

---

components/scripts/lib/build-scan-dump.sh
components/scripts/lib/build-scan-parse.sh

This resolves an issue when running with the latest scripts version and `build-scan-support-tool-0.0.4.jar` in which the Git details would not be displayed:
Previously, the build validation scripts read Git details from the CSV returned by the `build-scan-support-tool.jar`. The tool read this information from the custom values added by the CCUD plugin on the Build Scan. As of `0.0.4` the tool does not read custom values and the Git details are returned to the build validation scripts as `null`.
This _is_ different than how the `fetch-build-scan-data-cmdline-tool` works. It does read Git details from custom values and they are passed back to the build validation scripts in the CSV.
However, Git details are _not_ sourced from the CSV for `exp2-gradle`, `exp3-gradle`, `exp1-maven`, and …

Only read build cache metrics when Build Scan publishing is disabled

---

components/scripts/lib/config.sh

```
./02-validate-local-build-caching-different-locations.sh \
-r https://github.com/apache/maven \
-g package -x -e
```
---
```
./02-validate-local-build-caching-different-locations.sh \
-r https://github.com/apache/maven \
-g package -e
```
---
```
./02-validate-local-build-caching-different-locations.sh \
-r https://github.com/apache/maven \
-g package -e -s https://ge.solutions-team.gradle.com
```
```
./03-validate-local-build-caching-different-locations.sh \
-r https://github.com/etiennestuder/java-ordered-properties \
-t assemble -x -e
```
---
```
./03-validate-local-build-caching-different-locations.sh \
-r https://github.com/etiennestuder/java-ordered-properties \
-t assemble -e
```
---
```
./03-validate-local-build-caching-different-locations.sh \
-r …
```

Remove special Maven check when `-e` is used

---

components/scripts/gradle/01-validate-incremental-building.sh
components/scripts/gradle/02-validate-local-build-caching-same-location.sh
components/scripts/gradle/03-validate-local-build-caching-different-locations.sh
components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh
components/scripts/lib/gradle.sh
components/scripts/lib/paths.sh

Ran experiments 1, 2, & 3 for Gradle 5.x, 6.x, 7.x, & androidx and verified all succeeded:
```
./01-validate-incremental-building.sh -r git@github.com:gradle/ge-solutions.git -p sample-projects/gradle/5.x/ge -t 'build'
./01-validate-incremental-building.sh -r git@github.com:gradle/ge-solutions.git -p sample-projects/gradle/6.x/ge -t 'build'
./01-validate-incremental-building.sh -r git@github.com:gradle/ge-solutions.git -p sample-projects/gradle/7.x/ge -t 'build'
./01-validate-incremental-building.sh -r git@github.com:gradle/androidx.git -p biometric -t 'buildOnServer zipTestConfigsWithApks test' -a '-x ktlint' -s https://ge.solutions-team.gradle.com
./02-validate-local-build-caching-same-location.sh -r git@github.com:gradle/ge-solutions.git -p sample-projects/gradle/5.x/ge -t 'build' …
```

Fix initialization script does not exist

---

build.gradle.kts

This should ensure `createReleaseTag` is executed after `build` whenever `build githubRelease` is requested.

Fix createReleaseTag ordering

---

build.gradle.kts

Rather than having an explicit dependency from `generateChecksums` to the `assembleScript` Zip tasks, this change declares the two tasks as being inputs to `generateChecksums`
Fixes #308

Remove explicit task dependency for Gradle 8

---

.github/dependabot.yml

This is causing duplicate Dependabot PRs. For example, #317 and #318.

Remove redundant Dependabot configuration

---

components/scripts/gradle/gradle-init-scripts/configure-gradle-enterprise.gradle
components/scripts/gradle/gradle-init-scripts/enable-gradle-enterprise.gradle

This PR updates the Gradle Enterprise Gradle plugin version from `3.12.3` to `3.12.4` in the Gradle initialization scripts.

Bump com.gradle.enterprise from 3.12.3 to 3.12.4

---

components/scripts/gradle/01-validate-incremental-building.sh
components/scripts/lib/cli-parsers/gradle/01-cli-parser.m4
release/changes.md

1. #261
2. ⛄ #262
3. #263
4. #264
5. #265
6. #266
7. #267
8. #272
9. #274
10. #283
ℹ️ This PR continues the implementation of https://github.com/gradle/gradle-enterprise-build-validation-scripts/issues/206. This felt like a good place to stop. More PRs will be coming.
This PR introduces the following changes:
- The summary of Gradle experiment 1 now includes a `Performance Characteristics` section that includes `Effective task execution duration`
- Gradle experiment 1 can now be run with `-x` / `--disable-build-scan-publishing`
```sh
./01-validate-incremental-building.sh \
-r git@github.com:gradle/ge-solutions.git \
-p sample-projects/gradle/7.x/ge \
-t 'build'
```
```sh
./01-validate-incremental-building.sh \
-r git@github.com:gradle/ge-solutions.git \
-p …
```

Include performance characteristics and support `-x` for Gradle experiment 1 

---

README.md
buildSrc/build.gradle.kts
buildSrc/settings.gradle.kts
buildSrc/src/main/kotlin/ApplyArgbash.kt
buildSrc/src/main/kotlin/CreateGitTag.kt
components/capture-build-scan-url-maven-extension/build.gradle.kts
components/fetch-build-scan-data-cmdline-tool/build.gradle.kts

1. #261
2. #262
3. #263
4. #264
5. ⛄ #265
6. #266
7. #267
8. #272
9. #274
10. #283
This PR updates `buildSrc` to auto-provision the required JVM toolchains using the [Foojay Toolchains Plugin](https://github.com/gradle/foojay-toolchains) and sets the distribution vendor to `AZUL`. 
Additionally, I updated `buildSrc` to use the `kotlin-dsl` plugin. See [this comment for context](https://github.com/gradle/gradle-enterprise-build-validation-scripts/pull/260#issuecomment-1366705438)
Closes #254

Adopt Foojay Toolchains and Kotlin DSL plugins in build logic

---

components/scripts/gradle/04-validate-remote-build-caching-ci-ci.sh
components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh
components/scripts/lib/build_scan.sh
components/scripts/lib/config.sh
components/scripts/lib/info.sh
components/scripts/lib/java.sh
components/scripts/maven/03-validate-remote-build-caching-ci-ci.sh
components/scripts/maven/04-validate-remote-build-caching-ci-local.sh

1. #261
2. #262
3. #263
4. #264
5. #265
6. ⛄ #266
7. #267
8. #272
9. #274
10. #283
This PR adds a global `debug_mode` variable that can queried throughout the scripts. Previously the variable generated by Argbash was being used. 
Closes #180

Add variable to query debug mode

---

components/scripts/lib/java.sh

1. #261
2. #262
3. #263
4. #264
5. #265
6. #266
7. ⛄ #267
8. #272
9. #274
10. #283
This PR updates the Java launch code used to invoke the command line tools. 
Closes #176
In order to test this, I ran Gradle experiments 1-3 both online and offline:
```sh
./01-validate-incremental-building.sh -r git@github.com:gradle/ge-solutions.git -p sample-projects/gradle/7.x/ge -t 'build'
./01-validate-incremental-building.sh -r git@github.com:gradle/ge-solutions.git -p sample-projects/gradle/7.x/ge -t 'build' -x
./02-validate-local-build-caching-same-location.sh -r git@github.com:gradle/ge-solutions.git -p sample-projects/gradle/7.x/ge -t 'build'
./02-validate-local-build-caching-same-location.sh -r git@github.com:gradle/ge-solutions.git -p sample-projects/gradle/7.x/ge -t 'build' -x …
```

Modernize Java launch code

---

components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/api/client/GradleEnterpriseApiClient.java
components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/cli/FetchBuildValidationDataCommand.java
components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/cli/Fields.java
components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/model/BuildValidationData.java
components/scripts/gradle/01-validate-incremental-building.sh
components/scripts/lib/build-scan-parse.sh
components/scripts/lib/info.sh
release/changes.md

1. #261
2. #262
3. #263
4. #264
5. #265
6. #266
7. #267
8. ⛄ #272
9. #274
10. #283
ℹ️ This PR continues the implementation of https://github.com/gradle/gradle-enterprise-build-validation-scripts/issues/206. This felt like a good place to stop. More PRs will be coming.
This PR updates the summary of all experiments to display the serialization factor of the first build. For example:
To test this, I ran the following experiments and verified they displayed the serialization factor.
```sh
./01-validate-incremental-building.sh -r git@github.com:junit-team/junit5.git -t 'assemble' -s https://ge.solutions-team.gradle.com --debug
./01-validate-incremental-building.sh -r git@github.com:gradle/ge-solutions.git -p sample-projects/gradle/7.x/ge -t 'build' -x --debug …
```

Display serialization factor in summary of all experiments

---

components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/cli/Fields.java
components/scripts/lib/build-scan-parse.sh
components/scripts/lib/info.sh

1. #261
2. #262
3. #263
4. #264
5. #265
6. #266
7. #267
8. #272
9. ⛄ #274
10. #283
ℹ️ This PR continues the implementation of https://github.com/gradle/gradle-enterprise-build-validation-scripts/issues/206. This felt like a good place to stop. More PRs will be coming.
This PR adds the `potential_build_time` and `potential_build_time_savings`, which is calculated as:
```
potential_build_time = build_2_effective_duration - (build_2_executed_cacheable_duration / build_2_serialization_factor)
potential_build_time_savings = build_1_effective_duration - potential_build_time
```
This is then displayed to the user as in the following example:
These changes were tested by running the following experiments and verifying they display a potential build time and potential build time …

Display potential build time savings in experiment summaries

---

components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/cli/FetchBuildValidationDataCommand.java
components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/cli/Fields.java
components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/model/BuildValidationData.java
components/scripts/gradle/01-validate-incremental-building.sh
components/scripts/gradle/02-validate-local-build-caching-same-location.sh
components/scripts/gradle/03-validate-local-build-caching-different-locations.sh
components/scripts/gradle/04-validate-remote-build-caching-ci-ci.sh
components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh
components/scripts/lib/build-scan-parse.sh
components/scripts/lib/info.sh
components/scripts/maven/01-validate-local-build-caching-same-location.sh
components/scripts/maven/02-validate-local-build-caching-different-locations.sh
components/scripts/maven/03-validate-remote-build-caching-ci-ci.sh
components/scripts/maven/04-validate-remote-build-caching-ci-local.sh

1. #261
2. #262
3. #263
4. #264
5. #265
6. #266
7. #267
8. #272
9. #274
10. ⛄ #283
This PR cleans up and simplifies the contract of the Build Scan CSV sent by the command line tools. This is the final PR for implementing #206. 
ℹ️ This PR is related to gradle/ge#19681 which contains the corresponding changes to support offline processing.
Examples:
To test this, I ran all of the following experiments and examined their output was as expected. For those experiments using `-x`, I used the latest version of the `build-scan-support-tool` based on the changes in gradle/ge#19681. 
```sh
./01-validate-incremental-building.sh -r git@github.com:gradle/androidx.git -p biometric -t 'buildOnServer' -s https://ge.solutions-team.gradle.com -x …
```

Update the contract of command line tools

---

Gradle.md
Maven.md

Here's a quick link to what this looks like rendered in the README: https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/no/add-ticks/Gradle.md#investigating-file-resources-on-the-local-file-system

Add ticks to improve readability of file path

---

components/scripts/lib/gradle.sh
components/scripts/lib/maven.sh
release/changes.md

This PR changes how extra arguments (`-a` / `--args`) are parsed for both Maven and Gradle. Consider the following experiment:
```shell
./01-validate-incremental-building.sh \
-r https://github.com/gradle/common-custom-user-data-gradle-plugin \
-t build \
-a '--no-configuration-cache -Pfooo=barr -Pfoo=bar -Porg.gradle.jvmargs=-Xmx1g\ -XX:MaxMetaspaceSize=512m'
```
Previously, both executions would fail with the following error:
Regardless of how you quote wrap or escape the arguments, the result will be the same. 
This PR updates the logic to parse the additional arguments to use a more sophisticated approach. With these changes, the above example completes successfully:
Fixes #299

Fix incorrect parsing of additional argument values containing spaces

---

components/scripts/gradle/01-validate-incremental-building.sh
components/scripts/gradle/02-validate-local-build-caching-same-location.sh
components/scripts/gradle/03-validate-local-build-caching-different-locations.sh
components/scripts/gradle/04-validate-remote-build-caching-ci-ci.sh
components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh
components/scripts/lib/info.sh
components/scripts/maven/01-validate-local-build-caching-same-location.sh
components/scripts/maven/02-validate-local-build-caching-different-locations.sh
components/scripts/maven/03-validate-remote-build-caching-ci-ci.sh
components/scripts/maven/04-validate-remote-build-caching-ci-local.sh

The quick links are now identical across most Gradle experiments, and all of
the Maven quick links are identical across Maven experiments.

Deduplicate printing the quick links

---

components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/api/client/GradleEnterpriseApiClient.java
components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/cli/Fields.java
components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/model/BuildValidationData.java
components/scripts/gradle/01-validate-incremental-building.sh
components/scripts/lib/build-scan-parse.sh
components/scripts/lib/info.sh

This PR updates the performance characteristics section to display 3 "build time" metrics. They are:
- Initial build time: The build time of the first build
- Instant build time savings: The immediate savings as a result of build caching. 
- Pending build time savings: An estimate of the potential savings if all executed cacheable tasks had come from cache.
Example output of Gradle experiments 2-5 and Maven experiments 1-4:
```
Performance Characteristics
---------------------------
Initial build time:              16.284s
Build time with instant savings: 3.520s, 12.764s savings
Build time with pending savings: 3.520s, 0.000s additional savings
Avoided cacheable tasks:          63 tasks, 1m 21.524s total saved execution time
Executed cacheable tasks:          0 tasks, 0.000s total …
```

Update performance characteristics to show initial, instant, and pending build times

---

components/capture-build-scan-url-maven-extension/src/main/java/com/gradle/CaptureBuildScansListener.java
components/scripts/gradle/01-validate-incremental-building.sh
components/scripts/gradle/02-validate-local-build-caching-same-location.sh
components/scripts/gradle/03-validate-local-build-caching-different-locations.sh
components/scripts/gradle/04-validate-remote-build-caching-ci-ci.sh
components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh
components/scripts/gradle/gradle-init-scripts/configure-gradle-enterprise.gradle
components/scripts/lib/build-scan-parse.sh
components/scripts/lib/build_scan.sh
components/scripts/lib/gradle.sh
components/scripts/lib/info.sh
components/scripts/lib/maven.sh
components/scripts/maven/01-validate-local-build-caching-same-location.sh
components/scripts/maven/02-validate-local-build-caching-different-locations.sh
components/scripts/maven/03-validate-remote-build-caching-ci-ci.sh
components/scripts/maven/04-validate-remote-build-caching-ci-local.sh

Previously, the build validation scripts depended on the order build scans were
written to the build_scans.csv file, but this led to subtle and weird bugs,
particularly if the JVM running the build exits unexpectedly (such as in
response to an OutOfMemoryError).
This commit reworks things so that each row in the build_scans.csv file is
directly associated with the experiment build that generated it. When reading
build scan data, the association is re-established by matching build scan ids
with those that were produced by the builds.
A few other changes were made so that the build summary output makes sense,
particularly if the first build fails because the JVM exits unexpectedly.
Fixes #275

Better handle cases where builds fail because the JVM exits unexpectedly

---

components/scripts/lib/gradle.sh
components/scripts/lib/maven.sh

This PR fixes the extra arguments parsing to be compatible on all tested platforms. You will notice that changes have only been made to whitespace. This change specifically uses the same whitespace as it appears on the referenced Stack Overflow post.
I tested these changes using the same command as was used in #305.
```shell
./01-validate-incremental-building.sh \
-r https://github.com/gradle/common-custom-user-data-gradle-plugin \
-t build \
-a '--no-configuration-cache -Pfooo=barr -Pfoo=bar -Porg.gradle.jvmargs=-Xmx1g\ -XX:MaxMetaspaceSize=512m'
```
See here for a successful cross-platform tests run: https://github.com/gradle/gradle-enterprise-build-validation-scripts/actions/runs/4371353377

Fix parsing of extra arguments for all platforms

---

components/scripts/lib/summary.sh

Include the same non-cacheable tasks as used in the avoidable-cacheable tasks calculation.

Include specific non-cacheable tasks in comparison quick links

---

components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/cli/ConsoleLogger.java
components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/cli/FetchBuildValidationDataCommand.java
release/changes.md

Some users have builds which produce a lot of Build Scan data, and so it can
sometimes take a while to fetch the data for all of the builds. Fetching the
Build Scan data in parallel provides a nice performance boost for such users.
In order to do this safely, the logging format needed to be adjusted and made
stateless (before we were tracking some state to provide a more concise log
output format).
Fixes #349

Fetch Build Scan data in parallel

---

components/scripts/lib/build-scan-parse.sh

readonly always creates a global (readonly) variable. Doing this in a function
makes it likely an error message will be displayed because of repeated attempts
to redefine the same read-only global variable.

Create a local readonly var instead of a global one

---

components/scripts/gradle/04-validate-remote-build-caching-ci-ci.sh
components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh
components/scripts/lib/build-scan-parse.sh
components/scripts/maven/03-validate-remote-build-caching-ci-ci.sh
components/scripts/maven/04-validate-remote-build-caching-ci-local.sh

This commit also removes the parse_build_scan_url function because it turns out
it is not needed anymore.

Fix Gradle Experiment 5 and Maven Experiment 4 to pass the 1st build scan URL to the fetch utility

---

components/scripts/gradle/gradle-init-scripts/configure-gradle-enterprise.gradle
components/scripts/gradle/gradle-init-scripts/configure-local-build-caching.gradle
components/scripts/gradle/gradle-init-scripts/configure-remote-build-caching.gradle

Given a Gradle version older than 7.1, when `-XX:+UseParallelGC` is included as a JVM argument to the Gradle daemon, then user provided system properties from the command line are not available in certain parts of an Initialization script.
Any projects which are on a version of Gradle older than 7.1 and are supplying the JVM argument `-XX:+UseParallelGC` to the Gradle daemon. This can be done by setting the `org.gradle.jvmargs` property in `gradle.properties`.
```properties
org.gradle.jvmargs="-XX:+UseParallelGC"
```
In 2.3, it was decided to migrate all initialization script configuration to system properties. Previously, the configuration was a mix of system properties and project properties. The change was made to be consistent with the TeamCity initialization scripts, with itself, and …

Experiments can be run with parallel GC enabled on older Gradle versions

---

components/scripts/gradle/gradle-init-scripts/configure-gradle-enterprise.gradle
components/scripts/lib/gradle.sh

This PR adds back functionality that existed in previous versions of the build validation scripts (`2.2.1` and `2.2.0`) to not require a server URL to be configured when running with the `-x` / `--disable-build-scan-publishing`.
https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/v2.2.1/components/scripts/lib/gradle.sh#L22-L24

Do not require Gradle Enterprise server URL when Build Scan publishing is disabled

---

components/scripts/gradle/01-validate-incremental-building.sh
components/scripts/gradle/02-validate-local-build-caching-same-location.sh
components/scripts/gradle/03-validate-local-build-caching-different-locations.sh
components/scripts/gradle/04-validate-remote-build-caching-ci-ci.sh
components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh
components/scripts/lib/config.sh
components/scripts/maven/01-validate-local-build-caching-same-location.sh
components/scripts/maven/02-validate-local-build-caching-different-locations.sh
components/scripts/maven/03-validate-remote-build-caching-ci-ci.sh
components/scripts/maven/04-validate-remote-build-caching-ci-local.sh
release/changes.md

This PR adds validation for interactive mode to require `-s` when `e` is used. This brings consistency to how the scripts already work for non-interactive mode.
Previously, the experiments would fail with the error that a Gradle Enterprise server was not defined. 
This check only applies to Gradle 1-3 and Maven 1-2.
To test these changes, I ran all of the below experiments and verified all of them failed immediately. 
```
./01-validate-incremental-building.sh -r git@github.com:gradle/ge-solutions.git -b no-tool -p sample-projects/gradle/8.x/no-ge -t 'build' -i -e
./01-validate-incremental-building.sh -r git@github.com:gradle/ge-solutions.git -b no-tool -p sample-projects/gradle/8.x/no-ge -t 'build' -e
./02-validate-local-build-caching-same-location.sh -r …
```

Interactive mode requires `-s` when `-e` is used

---

components/scripts/lib/summary.sh
release/changes.md

This PR updates the serialization factor row in the performance characteristics summary to include the serialization factor from both builds. For example:

Performance characteristics includes the serialization factors of both builds

---

components/scripts/lib/build-scan-offline.sh
components/scripts/lib/build-scan-online.sh
components/scripts/lib/build-scan-parse.sh

An occurrence of the old `parse_build_scan_data` function name was still referenced in the offline processing flow. This PR updates it to use the new function `parse_build_scans_and_build_time_metrics`.
This change also consolidates the debug logging for printing build validation data to `build-scan-parse.sh`, where it used to be. Otherwise the same 4 lines would have to be duplicated to the offline flow as well.

New function name is used for offline processing

---

components/scripts/gradle/04-validate-remote-build-caching-ci-ci.sh
components/scripts/lib/build-scan-offline.sh
components/scripts/lib/build-scan-online.sh
components/scripts/lib/build-scan-parse.sh
components/scripts/maven/03-validate-remote-build-caching-ci-ci.sh

This PR makes several very minor improvements to the scripts code. These suggestions were from @jthurne on https://github.com/gradle/gradle-enterprise-build-validation-scripts/pull/383 but the PR had already been merged. 
This PR:
- f3bf09b54193585d3e8af716a9021322d2b22efa Adds a comment to the command used to parse Build Scan data by line
- b626997da7d0583007cb6bbec0dc6a00b0e683fd Makes all occurrences of `build_cache_metrics_only` and `all_data` consistently use single quotes
- 3a13ef32ff3fb4ab1b68a5666504efbfe4af3521 Greatly simplifies the parsing of build time metrics
I recommend reviewing each commit one at a time.

Scripts code is explained and more consistent

---

components/scripts/lib/build-scan-online.sh
release/changes.md

This change fixes a regression introduced by #383 where the conditions under which `--brief-logging` were incorrectly switched.
**Behavior in v2.3.2 (correct)**
**Behavior in v2.3.3 (incorrect)**
**Behavior with these changes (correct)**

Logging level when fetching Build Scan data from Gradle Enterprise is incorrect

---

components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/model/NumberedBuildScan.java
components/fetch-build-scan-data-cmdline-tool/src/test/java/com/gradle/enterprise/model/NumberedBuildScanTests.java
release/changes.md

This PR makes the Build Scan URL parsing logic much more resilient.
Previously, given a Build Scan URL with additional path parts after the ID, then parsing would fail. For example:
```
-1 https://e.grdev.net/s/meiwdomvrhneo/timeline \
-2 https://e.grdev.net/s/7fmkhoppnrpre/projects#:admin-database
```
This would result in:
Now, the same command results in a successful experiment and investigation quick links:

Build Scan URL parsing is more resilient 

---

components/scripts/gradle/04-validate-remote-build-caching-ci-ci.sh
components/scripts/lib/build-scan-offline.sh
components/scripts/lib/build-scan-online.sh
components/scripts/lib/build-scan-parse.sh
components/scripts/maven/03-validate-remote-build-caching-ci-ci.sh

This PR removes the `build_cache_metrics_only` and `all_data` values passed to and from various functions to control what summary data is parsed. The goal of this is to improve code readability by having one less variable to keep track of in the call stack.
The approach I decided to take was to set summary values only if they were empty. In the case of local experiments, a lot of the environmental summary values are already known. This approach prefers values determined by the scripts over those obtained from a Build Scan. Below is a summary of the changes:
- Previously, these fields were only set when `all_data` was passed to the parse function. Now, they are set when the current value is empty:
- `base_urls`
- `build_scan_urls`
- `git_repos`
- `git_branches`
- `git_commit_ids`
- …

Build Scan parsing is updated to read values when previously unknown

---

build.gradle.kts

* Add release notes to githubRelease body
* Use Provider.fileContents() to read `changes.md` and `version.txt` files
Execute `./gradlew githubRelease` with `dryRun.set(true)`
```
:githubRelease [This task is a dry run. All API calls that would modify the repo are disabled. API calls that access the repo information are not disabled. Use this to show what actions would be executed.]
:githubRelease [CHECKING FOR PREVIOUS RELEASE]
:githubRelease [EXISTING RELEASE FOUND https://github.com/gradle/gradle-enterprise-build-validation-scripts/releases/tag/development-latest]
:githubRelease [DELETING RELEASE Development Build]
:githubRelease [CREATING NEW RELEASE 
{
tag_name               = development-latest
target_commitish       = main
name                   = Development release …
```

Use Provider API to read version.txt and changes.md files

---

components/configure-gradle-enterprise-maven-extension/src/main/java/com/gradle/ConfigureGradleEnterprise.java
components/configure-gradle-enterprise-maven-extension/src/main/java/com/gradle/RootProjectExtractor.java
components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/api/client/AuthenticationConfigurator.java
components/scripts/gradle/gradle-init-scripts/configure-gradle-enterprise.gradle
components/scripts/lib/build-scan-online.sh
components/scripts/lib/build-scan-parse.sh

In #263 a change was made to always read the project name from the Gradle Enterprise API. All code around extracting the project name locally was removed. Unfortunately, the use case of not having access to the Gradle Enterprise API was not considered and therefore a regression was introduced. 
Currently, without these changes, if Gradle Enterprise API access is not configured, the project name will be unknown. 
With these changes, the project name will be shown even without Gradle Enterprise API access.
And for Maven (before | after):

Project names are displayed in summary when access to Gradle Enterprise API is not available

---

build.gradle.kts

Add release notes to githubRelease body
* Leverage Provider.fileContents() to support configuration caching when reading release notes file
Use configuration-cache-compatible Provider API to read version file
* Use configuration-cache-compatible Provider.fileContents() to read version file
1. Run `./gradlew clean build` and inspect jar versions
```
gradle-enterprise-build-validation-scripts % find . -name *.jar
./gradle/wrapper/gradle-wrapper.jar
./components/fetch-build-scan-data-cmdline-tool/build/libs/fetch-build-scan-data-cmdline-tool-2.3.6-all.jar
./components/fetch-build-scan-data-cmdline-tool/build/libs/fetch-build-scan-data-cmdline-tool-2.3.6.jar
./components/configure-gradle-enterprise-maven-extension/build/libs/configure-gradle-enterprise-maven-extension-2.3.6.jar …
```

Reading of the release version and description is configuration cache compatible

---

components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/cli/BuildScanDataFields.java
components/scripts/lib/build-scan-parse.sh

In #383, the build time field was superseded by the "initial" and "instant" build time fields. This PR removes all references to the build time field as it is no longer used.

Unused build time field is removed from Java command line tool response

---

build.gradle.kts

Keeping consistent with other repositories, get `tagName` from `githubRelease` extension when configuring `createReleaseTag` task.
***`createReleaseTag` - pushing the tag to the remote repository was disabled when executing these tests***
1. Execute `createReleaseTag` with `finalRelease` property set, and verify tag was properly created
```bash
gradle-enterprise-build-validation-scripts % git tag -l v2.3.6
gradle-enterprise-build-validation-scripts % ./gradlew -q clean createReleaseTag -PfinalRelease
gradle-enterprise-build-validation-scripts % git tag -l v2.3.6
v2.3.6
```
2. Execute `createReleaseTag` without `finalRelease` property set, and verify tag was properly created
```bash
tyler@tyler-mbp gradle-enterprise-build-validation-scripts % git tag -l development-latest
tyler@tyler-mbp …
```

Get tagName from githubRelease extension

---

build.gradle.kts

This makes consumption by the including build easier, in particular when supporting both final versions (from GitHub) and development versions (built via composite).

Zipped files are exposed as artifacts

---

.github/actions/gradle/experiment-config-cache/action.yml

The experiment-config-cache GH action is not supporting multiple build experiment runs as we are looking explicitly for [one single execution](https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/9f93fa0ea247622b2e2375f322647502fd8e34bd/.github/actions/gradle/experiment-config-cache/action.yml#L31).
This PR fixes https://github.com/gradle/gradle-enterprise-build-validation-scripts/issues/429

Allow configuration cache assertions to support multiple build runs

---

components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/api/client/GradleEnterpriseApiClient.java
release/changes.md

This is to help address issues caused by recently published build scans not yet being ready for consumption from the Gradle Enterprise API. Prior to this change, if a build scan was not yet available, the scripts would fail and the experiment summary would not be shown.

API requests allow some time for build scans to become available

---

build.gradle.kts
components/configure-gradle-enterprise-maven-extension/build.gradle.kts
components/scripts/lib/gradle.sh
release/changes.md

This PR bumps the versions of the Gradle Enterprise Gradle plugin and extension to the latest.
This means Gradle Enterprise 2023.1 or newer is required when using the `-e` command line option.

Latest Gradle Enterprise Gradle plugin and extension are used with `-e` command line option

---

build.gradle.kts
components/configure-gradle-enterprise-maven-extension/build.gradle.kts

Reverts gradle/gradle-enterprise-build-validation-scripts#466
We don't want to bump the Maven extension version before the release.

Revert "Bump com.gradle:gradle-enterprise-maven-extension from 1.17.4 to 1.18"

---

components/scripts/gradle/gradle-init-scripts/configure-local-build-caching.gradle
components/scripts/gradle/gradle-init-scripts/configure-remote-build-caching.gradle
release/changes.md

This PR removes the parent build checks at the beginning of the build caching init scripts.
These checks were preventing the caching configuration from being to child builds and resulted in a warning on the build cache performance screen ([Example](https://ge.solutions-team.gradle.com/s/s4fyn6jagmbec/performance/build-cache)). 
Here are some tests I ran to verify the changes:
| Project | Before | After |
|--------|--------|--------|
| AndroidX | [warning](https://ge.solutions-team.gradle.com/s/5e2yf3svxah3y/performance/build-cache) | [no warning](https://ge.solutions-team.gradle.com/s/kgstgs56jpaz2/performance/build-cache) |
| Caffeine | [warning](https://ge.solutions-team.gradle.com/s/5wco2hntuo7de/performance/build-cache) | [no …

Build caching init scripts are applied to all builds

---

Gradle.md
Maven.md
components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/cli/FetchBuildScanDataCommand.java
components/scripts/lib/build-scan-offline.sh
components/scripts/lib/build-scan-online.sh
release/changes.md

Users can use `CLIENT_JAVA_HOME` to override which JVM is used to execute the
Build Scan clients.  The other JVMs used (for running Gradle and for building
code) are not affected.
Fixes #428

Add support for CLIENT_JAVA_HOME

---

build.gradle.kts
components/configure-gradle-enterprise-maven-extension/build.gradle.kts
components/scripts/lib/gradle.sh
release/changes.md

This PR bumps the versions of the injected Gradle Enterprise Gradle plugin and extension to the latest.
This means Gradle Enterprise 2023.2 or newer is required when using the -e command line option.

Support is dropped for Gradle Enterprise versions older than 2023.2 when using `-e` command line option

---

components/scripts/lib/build-scan-offline.sh

Adds specific error handling for an invalid JVM version. Other non-zero exit codes are treated as an unexpected error.
Below are all of the test cases I ran to verify these changes.
```shell
$ java -version            
openjdk version "1.8.0_362"
$ ./03-validate-local-build-caching-different-locations.sh -r git@github.com:gradle/ge-solutions.git -p sample-projects/gradle/8.x/ge -t 'build' -x
```
This results in the following:
```shell
$ java -version            
openjdk version "1.8.0_362"
$ CLIENT_JAVA_HOME="$JDK17" ./03-validate-local-build-caching-different-locations.sh -r git@github.com:gradle/ge-solutions.git -p sample-projects/gradle/8.x/ge -t 'build' -x
```
This results in the following:
```shell
$ java -version
openjdk version "17.0.6" 2023-01-17
$ …
```

Invalid JVM version error message is handled in the scripts 

---

.github/workflows/cross-platform-testing-build-from-source.yml
.github/workflows/cross-platform-testing-use-development-release.yml

This PR updates the version of Ubuntu from 20.04 to 22.04 to resolve issues with the certificate verification seen here: https://github.com/gradle/gradle-enterprise-build-validation-scripts/actions/runs/6435049099/job/17475524181

Bump WSL distribution from Ubuntu-20.04 to Ubuntu-22.04

---

components/fetch-build-scan-data-cmdline-tool/src/main/openapi/openapi.yaml

This PR adds support for Develocity instances running 2023.3.2 and greater when creating the experiment summary. 
This resolves the `ERROR: The required field 'isDisabledDueToError' is not found in the JSON string: {"isEnabled":false}` that is seen when running the scripts with a Develocity instance running 2023.3.2.
Before: https://github.com/gradle/gradle-enterprise-build-validation-scripts/actions/runs/6543580559/job/17768404455#step:7:84
After: https://github.com/gradle/gradle-enterprise-build-validation-scripts/actions/runs/6566328643/job/17837095215#step:8:84

Support Develocity API 2023.3.2+ for building experiment summary

---

Gradle.md
Maven.md
README.md

This renames Gradle Enterprise to Develocity in the README and no other files.

Gradle Enterprise is renamed to Develocity

---

Gradle.md
Maven.md

This change updates the headers for the places that are linked to from the BVS code themselves in order to avoid broken links.

Revert Readme headers to Gradle Enterprise that are linked to from the scripts

---

components/scripts/lib/gradle.sh

This PR bumps the injected Common Custom User Data Gradle plugin version from 1.12.3 to 1.13.

Bump injected Common Custom User Data Gradle plugin version from 1.12.2 to 1.13

---

settings.gradle.kts

This PR upgrades the Develocity Gradle plugin to 3.17 and migrates to the corresponding new APIs.

Upgrade build to use Develocity Gradle plugin 3.17

---

buildSrc/src/main/kotlin/ApplyArgbash.kt

argbash uses `#!/bin/bash`. On MacOS, this means the MacOS version of bash will
be used. This wasn't a problem in the past, but it appears to be an issue now
(maybe because of a change to one of the recent Gradle versions, or maybe
because of a recent MacOS update). When MacOS bash was used, argbash would fail
with a syntax error. This is because it uses bash features that are not
available in the MacOS version of bash.
The solution is to use /usr/bin/env bash to invoke argbash, which then uses
whatever version of bash is first on the system path. For MacOS developers,
this will be a more recent GNU version of bash.

Fix running argbash on MacOS

---

build.gradle.kts
components/scripts/lib/build-scan-online.sh

Dependabot does not upgrade Shellcheck because it isn't declared like a normal dependency.
Also addresses [SC2004](https://www.shellcheck.net/wiki/SC2004), which was detected by the new version of shellcheck.

Upgrade Shellcheck to v0.10.0

---

.github/actions/gradle/experiment-1/action.yml
.github/actions/gradle/experiment-2/action.yml
.github/actions/gradle/experiment-3/action.yml
.github/actions/maven/experiment-1/action.yml
.github/actions/maven/experiment-2/action.yml

Currently the GitHub actions for executing the experiments does not include a way to enable debug logging for the validation scripts. This is problematic if there is an issue that only reproduces in CI. This PR updates the experiment actions to read the default environment variable `RUNNER_DEBUG` to toggle debug logging for the validation scripts. If jobs are re-run with the "Enable debug logging" box checked, the `RUNNER_DEBUG` environment variable is set, and debug logging will be enabled for the validation scripts.

Enable debug logging for the validation scripts when GitHub Actions debug logging is enabled

---

.github/dependabot.yml
build.gradle.kts
components/configure-gradle-enterprise-maven-extension/build.gradle.kts
components/configure-gradle-enterprise-maven-extension/src/main/java/com/gradle/ConfigureDevelocity.java
components/configure-gradle-enterprise-maven-extension/src/main/java/com/gradle/ConfigureDevelocityAdaptor.java
components/configure-gradle-enterprise-maven-extension/src/main/java/com/gradle/ConfigureGradleEnterprise.java
components/configure-gradle-enterprise-maven-extension/src/main/resources/META-INF/plexus/components.xml
components/scripts/lib/maven.sh

The Gradle Enterprise Maven Extension was renamed to the Develocity Maven
Extension in version 1.21.  The API was also updated for hte product name
change. Unfortunately, this broke compatibility with the Build Validation
Scripts. This commit fixes the incompatibility.
The fix works by updating the configure-gradle-enterprise-maven-extension to
define and register two listeners: a GradleEnterpriseListener and a
DevelocityListener.  If an older version of the Gradle Enterprise Maven
Extension is used, it will load the GradleEnterpriseListener.  If a newer
version of the Develocity Maven Extension is used, then it will load the
DevelocityListener. The Develocity Maven Extension Adapters are used to
eliminate duplication between the two different listeners.
To ensure compatibility with older …

Add support for the renamed Develocity Maven Extension

---

.github/workflows/build-verification.yml
.github/workflows/cross-platform-testing-build-from-source.yml
.github/workflows/cross-platform-testing-use-development-release.yml
.github/workflows/development-release.yml
.github/workflows/production-release.yml

- Migrated GitHub actions gradle executions to access token auth 
- Migrated GitHub actions cross build tests of BVS env var access key to develocity naming

Github actions access token migration

---

.github/workflows/cross-platform-testing-build-from-source.yml
.github/workflows/cross-platform-testing-use-development-release.yml

GitHub does not offer MacOS 11 runners anymore so those workflows are failing.
https://github.com/gradle/gradle-enterprise-build-validation-scripts/actions/runs/10042207806
Supported versions are now 12, 13, & 14.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#standard-github-hosted-runners-for-public-repositories
Additionally, the PR updates the versions of each tested OS to the latest and adds Java 21.

Tested OS and Java versions are updated

---

.github/workflows/cross-platform-testing-build-from-source.yml
.github/workflows/cross-platform-testing-use-development-release.yml

Added the CCUD necessary env vars to the WSLENV for wsl-bash githubActions testing. 
Until now, cross-platform tests on windows, which use wsl-bash shell did not correctly pick up that this was executed on github actions. This is not an issue of CCUD, it's an issue of WSL, which by default doesn't "forward" env vars set in Windows (host) by default. The only way to forward them is to set them using `WSLENV` - see [discussion](https://github.com/Vampire/setup-wsl/discussions/9) and [Microsoft blog](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/). You can also observe that in this [test project](https://github.com/ribafish/kotlinTests/actions/runs/10146123467), where the env vars are printed out. All of them are available with the [default windows …

Fixed CCUD CI detection when using wsl-bash on GHA

---

.github/actions/gradle/experiment-1/action.yml
.github/actions/gradle/experiment-2/action.yml
.github/actions/gradle/experiment-3/action.yml
.github/actions/maven/experiment-1/action.yml
.github/actions/maven/experiment-2/action.yml

Fixes https://github.com/gradle/gradle-enterprise-build-validation-scripts/issues/644
Since [upload-artifact@v4](https://github.com/actions/upload-artifact), uploading again the same artifact name in a workflow fails the step.
Using a hardcoded `experiment-X-receipt` is not valid anymore
Use a unique name. This is not so straightforward as some collisions can occur in the case of matrix.
Using the `job-index` for matrix solves this.
Note that appending the `job-index` is happening only if `job-total > 1` to not suffix artifacts from non matrix scenario
This could hopefully get simplified if/when GitHub starts to expose a unique `job-id` when running with matrix strategy.
A receipt download link has been added as part of the workflow summary
See a summary running with the PR fix …

Use unique artifact identifier in upload-artifact step

---

components/scripts/lib/maven.sh
components/scripts/maven/01-validate-local-build-caching-same-location.sh
components/scripts/maven/02-validate-local-build-caching-different-locations.sh
components/scripts/maven/04-validate-remote-build-caching-ci-local.sh
release/changes.md

This PR adds the equivalent DV extension system property where the legacy GE extension system properties were used. This results in no deprecation warnings printed to the console, while retaining backwards compatibility.
Ran the below tests and verified no deprecation warnings were printed.
```shell
./01-validate-local-build-caching-same-location.sh -r git@github.com:gradle/maven-build-scan-quickstart.git -c feb731de5b279d3a941f81fb3d1845ec0405388b -g 'verify' -s https://ge.solutions-team.gradle.com
./01-validate-local-build-caching-same-location.sh -r git@github.com:gradle/maven-build-scan-quickstart.git -c feb731de5b279d3a941f81fb3d1845ec0405388b -g 'verify' -e -s https://ge.solutions-team.gradle.com
./01-validate-local-build-caching-same-location.sh -r …
```

Gradle Enterprise deprecation warnings aren't printed to the console for Maven builds using Develocity extension

---

Gradle.md
Maven.md

This adds a quick note to the READMEs that changes must still be committed when using a local Git repository.

Instructions include callout about committing for local Git repositories

---

components/configure-gradle-enterprise-maven-extension/build.gradle.kts
components/configure-gradle-enterprise-maven-extension/src/main/java/com/gradle/ConfigureDevelocityListener.java
components/configure-gradle-enterprise-maven-extension/src/main/java/com/gradle/ConfigureGradleEnterpriseListener.java
components/configure-gradle-enterprise-maven-extension/src/main/resources/META-INF/plexus/components.xml

This PR renames `ConfigureDevelocity` to `ConfigureDevelocityListener` and `ConfigureGradleEnterprise` to `ConfigureGradleEnterpriseListener` to better align with how listeners are named in other repositories. For example:
Some other minor adjustments were made also.

Listeners in bundled Maven extension are cleaned up and aligned with other Solutions repos

---

components/scripts/lib/cli-parsers/gradle/01-cli-parser.m4
components/scripts/lib/cli-parsers/gradle/02-cli-parser.m4
components/scripts/lib/cli-parsers/gradle/03-cli-parser.m4
components/scripts/lib/cli-parsers/maven/01-cli-parser.m4
components/scripts/lib/cli-parsers/maven/02-cli-parser.m4

This PR removes the `-x` argument from text displayed by `--help`.

Command line argument `-x` is removed from help text

---

components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh
components/scripts/lib/gradle.sh
release/changes.md

System properties cannot be read reliably from init scripts for older versions of Gradle. This is not the case for environment variables. This PR changes the configuration of the init scripts to be done using environment variables instead of system properties.

Use environment variables to configure Gradle init scripts

---

.github/actions/gradle/download/action.yml
.github/actions/maven/download/action.yml

This PR adds an additional optional parameter to download the latest development release of the scripts. If left unspecified, the latest released version will be downloaded.

Expose option to download latest development release in the download actions

---

build.gradle.kts
buildSrc/src/main/kotlin/TransformDevelocityInjectionScript.kt
components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh
components/scripts/gradle/gradle-init-scripts/configure-build-validation.gradle
components/scripts/gradle/gradle-init-scripts/configure-local-build-caching.gradle
components/scripts/gradle/gradle-init-scripts/configure-remote-build-caching.gradle
components/scripts/lib/gradle.sh
release/changes.md

This PR:
1) Reverts the change for configuring init scripts via environment variables
2) (re)Migrates init scripts to use `gradle.startParameter` to read system properties
I suggest reviewing only the last 2 commits as the first 2 only revert the previous changes.
Relevant diff: https://github.com/gradle/gradle-enterprise-build-validation-scripts/pull/682/files/64f48ec26c9fb43c51d62d281a9c3a99554342e1..632519d8c0cf14190fe3ac6608b72ac50fd791d4

Environment variable changes are reverted and `gradle.startParameter` is used to read system properties in init scripts

---

build.gradle.kts
components/scripts/gradle/gradle-init-scripts/configure-build-validation.gradle
components/scripts/lib/gradle.sh
settings.gradle.kts

> [!IMPORTANT]
> Will be merged when common Develocity injection script 1.1 is released.
> 
> Draft because gradle/develocity-ci-injection#10 must be merged and released before this can be merged. Changes could be required in the other PR causing updates to be required here.
This PR updates removes setting the server URL from the `configure-build-validation.gradle` script. This PR assumes gradle/develocity-ci-injection#10 will be merged.
It also adds the necessary configuration for the Develocity CI injection repository to be used as an included build:
```shell
./gradlew -PdevelocityCiInjectionProjectDir="../develocity-ci-injection" clean assemble
```
If `develocityCiInjectionProjectDir` isn't provided the script is resolved using Gradle dependency management.

Common Develocity injection script is used when setting Develocity server URL

---

.github/actions/gradle/README.md
.github/actions/gradle/download/action.yml
.github/actions/maven/README.md
.github/actions/maven/download/action.yml
.github/workflows/combine-dependabot-prs.yml
.github/workflows/cross-platform-testing-use-development-release.yml
Gradle.md
Maven.md
README.md
build.gradle.kts
components/scripts/README.md
components/scripts/lib/interactive-mode.sh

> [!CAUTION]
> This PR is not to be merged until the renaming has taken place. This is currently scheduled to happen on Dec 17 during EMEA morning. Check https://github.com/gradle/develocity-build-validation-scripts to verify the current state.
This PR renames references to the old Develocity Build Validation Scripts repository name to https://github.com/gradle/develocity-build-validation-scripts

References to the Develocity Build Validation Scripts repository are renamed

---

.github/workflows/cross-platform-testing-build-from-source.yml
.github/workflows/development-release.yml

Every GitHub release, including pre-releases, will notify any repository watchers. We were previously creating a new development release on every commit to `main`. This creates a lot of noise for anyone watching the repository. Many of these commits aren't meaningful enough to warrant creating a development release.
The reason we did this was so we could run the cross-version tests using the latest changes in main in the form of a distribution. We feel we've outgrown this need and are removing the automated development releases.
Instead, `main` will be tested by building from source and development releases will no longer be created on every commit. There will still be a way to create development releases manually for changes that are meaningful enough and need to be used before a proper …

Automatic development releases are removed

---

components/scripts/gradle/gradle-init-scripts/configure-build-validation.gradle

This change adds a new file `exceptions.txt` that writes the contents of the `error` payload to a file.

Exception is written to `exceptions.txt` file on build scan error

---

Gradle.md
Maven.md
components/scripts/lib/exit-code.sh
release/changes.md

When using the `--fail-if-not-fully-cacheable` option, the scripts will return with exit code `3` if the number of cacheable tasks/goals is > 0. The main use case for this feature is to fail a recurring CI build when build logic is introduced that causes build cache misses.
Previously, if `--fail-if-not-fully-cacheable` was used the Develocity API call to retrieve cacheability data failed, e.g., the default 10 second build ingest wait timeout was exceeded, the scripts would return with exit code `0` (successful). This is problematic because it's actually unknown whether or not the build is fully cacheable.
With these changes, if the number of executed cacheable tasks/goals is unknown for any reason and `--fail-if-not-fully-cacheable` is used, the scripts will return with exit code `4` …

Unsuccessful exit code returned when performance characteristics are unknown and `--fail-if-not-fully-cacheable` is used

---

components/scripts/lib/gradle.sh
release/changes.md

This was already the case for Maven.
https://github.com/gradle/develocity-build-validation-scripts/blob/12631715a9e1c045be0689b99f62a1e2d729f7f8/components/configure-develocity-maven-extension/src/main/java/com/gradle/ConfigureDevelocityAdaptor.java#L89-L93
https://ge.solutions-team.gradle.com/s/uy2vxghmxko6e#switches

Background Build Scan publication is always disabled for Gradle

---

build.gradle.kts
components/scripts/lib/build-scan-online.sh
release/changes.md

This change adds the `--availability-wait-timeout` option to the build scan summary tool invocation with a value of '60' when the `--fail-if-not-fully-cacheable` option is used.
This should increase the likelihood of experiment build scans being ingested in order to retrieve the required data from the Develocity API to determine cacheability.
The `availabilityWaitTimeoutSecs` query parameter is included on the Develocity API calls when the `--fail-if-not-fully-cacheable` option is included in the script invocation. 
When the `--fail-if-not-fully-cacheable` option isn't included, no `availabilityWaitTimeoutSecs` parameter is included in the Develocity API call.
Closes #505

Scripts wait longer for builds to ingest when `--fail-if-not-fully-cacheable` is used

---

components/scripts/gradle/gradle-init-scripts/configure-build-validation.gradle
release/changes.md

When running the scripts, we need to ensure a build scan is always published despite what the user has configured in their build.
This was previously already the case for the Build Scan and Gradle Enterprise plugins.

Build Scan publishing is enforced for the Develocity Gradle plugin

---

components/scripts/lib/init.sh

See issue #496 for the reason _why_ this was done.
For an explanation of _how_ it was done, see the code comment above the `generate_run_id` function that explains this in great detail. 
Example: https://ge.solutions-team.gradle.com/scans?search.names=Experiment%20run%20id&search.timeZoneId=America%2FChicago&search.values=1c87416e774b51d#selection.buildScanA=pn6cdtogklovg
Resolves #496

Experiment `run_id` is made significantly more random

---

.github/actions/gradle/experiment-1/action.yml
.github/actions/gradle/experiment-2/action.yml
.github/actions/gradle/experiment-3/action.yml
.github/actions/maven/experiment-1/action.yml
.github/actions/maven/experiment-2/action.yml

The GitHub summary is not published when the validation scripts run as part of the [GiHub composite actions](https://github.com/gradle/develocity-build-validation-scripts/tree/main/.github/actions) fail.
The validation scripts are run within a bash step which is by default configured to exit immediately upon command failure
```
set -e
```
The fix is to revert this configuration and capture the validation script exit code to allow post actions within the step (build scan links capture and receipt file renaming)
Subsequent steps to archive the receipt and inline it in the summary are configured to run unconditionnally
```
if: always()
```
- The receipt file is renamed to  a predictable receipt.txt file to avoid passing the filename across steps and adding an attack surface as the file …

Expose GitHub summary unconditionally
