components/scripts/gradle/gradle-init-scripts/configure-gradle-enterprise.gradle, components/scripts/gradle/gradle-init-scripts/enable-gradle-enterprise.gradle
Signed-off-by: Jerome Prinet <jprinet@gradle.com>
=> Bump up GE Gradle plugin to 3.9

.github/actions/gradle/experiment-1/action.yml, .github/actions/gradle/experiment-2/action.yml, .github/actions/gradle/experiment-3/action.yml
Tasks argument has to be protected to allow whitespaces
=> Fix tasks argument containing whitespaces

build.gradle.kts
This PR fixes a few tasks which were being created during the configuration
phase because they dereferenced task providers (transforming the providers
using map and flatMap fixes this).
Also eliminates the use of deprecated properties on the Checksum task.
=> Fix three tasks to be realized lazily

components/scripts/gradle/gradle-init-scripts/configure-gradle-enterprise.gradle, components/scripts/gradle/gradle-init-scripts/enable-gradle-enterprise.gradle
Update Gradle Enterprise Gradle Plugin 3.10.3 -> 3.11.1
=> Update Gradle Enterprise Gradle Plugin 3.10.3 -> 3.11.1

components/scripts/gradle/gradle-init-scripts/enable-gradle-enterprise.gradle
https://github.com/gradle/common-custom-user-data-gradle-plugin/releases/tag/v1.8.2
=> Upgrade Common Custom User Data to 1.8.2

components/scripts/gradle/01-validate-incremental-building.sh
=> Replace reference to local build cache with incremental build reference

components/scripts/gradle/gradle-init-scripts/configure-gradle-enterprise.gradle, components/scripts/gradle/gradle-init-scripts/enable-gradle-enterprise.gradle
Release notes: https://docs.gradle.com/enterprise/gradle-plugin/#release_history
=> Update Gradle Enterprise Gradle plugin to 3.12

components/scripts/gradle/04-validate-remote-build-caching-ci-ci.sh, components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh, components/scripts/lib/config.sh, components/scripts/maven/03-validate-remote-build-caching-ci-ci.sh, components/scripts/maven/04-validate-remote-build-caching-ci-local.sh, release/changes.md
**Note:** This is currently pointing to the branch for #240 due to the possibility of merge conflicts. #240 should be merged first.
```shell
./03-validate-remote-build-caching-ci-ci.sh \
-1 'https://ge.solutions-team.gradle.com/s/ed6a3h7m3swpa' \
-2 'https://ge.solutions-team.gradle.com/s/eq5u5tbq6xdyo' \
--debug \
--interactive
```
```shell
./04-validate-remote-build-caching-ci-local.sh \
-1 'https://ge.solutions-team.gradle.com/s/ed6a3h7m3swpa' \
--args '-DskipTests' \
--remote-build-cache-url 'https://ge.solutions-team.gradle.com/cache' \
--debug \
--interactive
```
```shell
-1 https://ge.solutions-team.gradle.com/s/k2gzrbklej2eq \
-2 https://ge.solutions-team.gradle.com/s/2dn2py4gxhm7y \
--debug \
--interactive
```
```shell …
```
=> Include `-d` in the command to repeat experiment

components/capture-build-scan-url-maven-extension/src/main/java/com/gradle/CaptureBuildScansListener.java
=> Force CaptureBuildScansListener to read GE server URL after it is set

components/scripts/lib/gradle.sh, components/scripts/lib/maven.sh, components/scripts/lib/paths.sh
=> Do not use pushd "" as behavior can be unexpected when used with CDPATH

components/scripts/gradle/04-validate-remote-build-caching-ci-ci.sh, components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh, components/scripts/lib/config.sh, components/scripts/maven/03-validate-remote-build-caching-ci-ci.sh, components/scripts/maven/04-validate-remote-build-caching-ci-local.sh, release/changes.md
```shell
./03-validate-remote-build-caching-ci-ci.sh \
-1 'https://ge.solutions-team.gradle.com/s/ed6a3h7m3swpa' \
-2 'https://ge.solutions-team.gradle.com/s/eq5u5tbq6xdyo' \
--debug \
--interactive
```
```shell
./04-validate-remote-build-caching-ci-local.sh \
-1 'https://ge.solutions-team.gradle.com/s/ed6a3h7m3swpa' \
--args '-DskipTests' \
--remote-build-cache-url 'https://ge.solutions-team.gradle.com/cache' \
--debug \
--interactive
```
```shell
-1 https://ge.solutions-team.gradle.com/s/k2gzrbklej2eq \
-2 https://ge.solutions-team.gradle.com/s/2dn2py4gxhm7y \
--debug \
--interactive
```
```shell
./05-validate-remote-build-caching-ci-local.sh \
-1 https://ge.solutions-team.gradle.com/s/s7p73cvpbjua4 \
-u …
```
=> Fix debug flag in command to repeat experiment

components/scripts/gradle/gradle-init-scripts/configure-gradle-enterprise.gradle, components/scripts/lib/gradle.sh
```
./03-validate-local-build-caching-different-locations.sh \
-r https://github.com/etiennestuder/java-ordered-properties \
-t assemble -s https://ge.solutions-team.gradle.com
```
---
```
./03-validate-local-build-caching-different-locations.sh \
-r https://github.com/etiennestuder/java-ordered-properties \
-t assemble -x
```
---
```
./03-validate-local-build-caching-different-locations.sh \
-r https://github.com/etiennestuder/java-ordered-properties \
-t assemble -b no-ge -x -e
```
=> Remove dummy Gradle Enterprise server URL

.github/actions/gradle/download/action.yml, .github/actions/maven/download/action.yml
=> Add retry mechanism to curl instruction

components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/api/client/GradleEnterpriseApiClient.java
This PR cleans up the method naming and improves code consistency.
=> Improve method naming and consistency

components/scripts/gradle/01-validate-incremental-building.sh, components/scripts/gradle/02-validate-local-build-caching-same-location.sh, components/scripts/gradle/03-validate-local-build-caching-different-locations.sh, components/scripts/gradle/05-validate-remote-build-caching-ci-local.sh
=> No longer include --scan when displaying the build command

components/capture-build-scan-url-maven-extension/src/main/java/com/gradle/CaptureBuildScansListener.java, components/scripts/gradle/gradle-init-scripts/configure-gradle-enterprise.gradle, components/scripts/lib/gradle.sh, components/scripts/lib/maven.sh
This PR adds the build validation scripts version as a custom value to executed builds. 
- Gradle: https://ge.solutions-team.gradle.com/s/wzntvwjjdcajm/custom-values#L0
- Maven: https://ge.solutions-team.gradle.com/s/6eymkkmgysalo/custom-values#L0
fixes #230
=> Add build validation scripts version as custom value

.github/workflows/cross-platform-testing.yml
Build Scan links have also been updated.
=> All experiments are run during cross-platform tests

components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/cli/BuildInsightsPrinter.java, components/fetch-build-scan-data-cmdline-tool/src/main/java/com/gradle/enterprise/cli/FetchBuildScanDataCommand.java
This PR applies some changes from comments left by @jthurne on #383.
=> Java tool printing logic is simplified

Gradle.md, Maven.md, components/scripts/lib/summary.sh
=> Performance characteristics are explained in README and link included in experiment summary

components/scripts/gradle/01-validate-incremental-building.sh, components/scripts/lib/summary.sh
=> Performance characteristics details link is moved to footer

components/scripts/lib/gradle.sh
This PR updates the injected CCUD Gradle plugin version from 1.10 to 1.11.
=> Bump injected CCUD Gradle plugin version from 1.10 to 1.11

.github/workflows/combine-dependabot-prs.yml
Added the combine dependabot prs GHA workflow. As a template I took the workflow file from https://github.com/gradle/common-custom-user-data-gradle-plugin/pull/187
=> Added the combine dependabot prs GHA workflow.

components/scripts/lib/gradle.sh
Bumped CCUD gradle plugin version (1.11.3) applied when ge is injected
=> Bumped CCUD gradle plugin version (1.11.3) applied when ge is injected

components/scripts/lib/gradle.sh
Fixed wrong gradle CCUD plugin version bump - correct version it 1.11.2
=> Fixed wrong gradle CCUD plugin version bump - correct version it 1.11.2

components/scripts/lib/gradle.sh
Update:
```
args+=("-Dcom.gradle.enterprise.build-validation.ccud.plugin.version=1.11.3")
```
=> Updating ccud gradle 

components/scripts/lib/gradle.sh
This PR bumps the injected Common Custom User Data Gradle plugin version from 1.12 to 1.12.2.
=> Bump injected Common Custom User Data Gradle plugin version from 1.12 to 1.12.2

.github/actions/gradle/experiment-config-cache/action.yml, .github/workflows/build-verification.yml, .github/workflows/cross-platform-testing-build-from-source.yml, .github/workflows/development-release.yml, .github/workflows/production-release.yml
Migrated to gradle/actions/setup-gradle@v3 and removed info logging from build-verification as discussed in PR https://github.com/gradle/gradle-enterprise-build-validation-scripts/pull/633
=> Migrated to gradle/actions/setup-gradle@v3 and removed info logging from build-verification

components/scripts/lib/gradle.sh, release/changes.md
The wrong property was being used.
=> CCUD injection is fixed for Gradle builds
